POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "adam11",
  "name": "Adam Richard",
  "password": "ric",
  "gender": "male",
  "location": "Detroit"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "adam_richar",
  "password": "richard_56"
}

###
PUT  http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "adam_richard",
  "oldPassword": "richard@123",
  "newPassword": "rich"
}